apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-readiness-patch
  namespace: monitoring
data:
  patch.yaml: |
    spec:
      template:
        spec:
          containers:
          - name: grafana
            readinessProbe:
              httpGet:
                path: /api/health
                port: 3000
              initialDelaySeconds: 10
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 10
            livenessProbe:
              httpGet:
                path: /api/health
                port: 3000
              initialDelaySeconds: 60
              timeoutSeconds: 10
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 10
